language: node_js
node_js:
  - 10
  - 12
  - 14

install:
  - yarn install
  - yarn add global codecov

script:
  - yarn test
  - codecov

jobs:
  include:
    - stage: release
      node_js: lts/*
      before_deploy:
        - yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
      after_deploy:
        - test ! -e /home/travis/.npm/_logs ; TRAVIS_TEST_RESULT=$?
